#!/bin/bash

 docker run --rm -it --device /dev/dri --network host -e DISPLAY=$DISPLAY -e XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR -v /etc/machine-id:/etc/machine-id:ro -v /run/user/1000/pulse:/run/user/1000/pulse -v $HOME/.Xauthority:/home/mpv/.Xauthority ani-cli $@

